apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: operate
    demo: "true"
  name: operate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operate
  template:
    metadata:
      labels:
        app: operate
      annotations:
        instrumentation.opentelemetry.io/inject-python: "python-instrumentation"
    spec:
      containers:
      - image: lrbono/operate:latest
        name: operate
        imagePullPolicy: Always
        env:
          - name: "APP_NAME"
            value: "operate"
          - name: "APP_NAMESPACE"
            value: "app"
          - name: "PORT"
            value: "80"
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
