apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
    demo: "true"
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "nodejs-instrumentation"
    spec:
      containers:
      - image: lrbono/opentelemetrymicroservicestestapp_front:latest
        name: front
        imagePullPolicy: Always
        env:
          - name: "APP_NAME"
            value: "front"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
