# instrumentation.yml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python
  namespace: app
spec:
  exporter:
    # endpoint: http://daemonset-collector.opentelemetry-collectors:4318
    endpoint: http://gateway-collector.opentelemetry-collectors:4318
  propagators:
    - tracecontext
    - baggage
    # - b3
  sampler:
    # type: always_on
    type: parentbased_traceidratio
    argument: '1'    
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
  # https://opentelemetry.io/docs/kubernetes/operator/automatic/
    env:
      - name: "OTEL_PYTHON_LOG_CORRELATION"
        value: "true"
      # - name: OTEL_LOGS_EXPORTER
      #   value: otlp_proto_http
      # - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
      #   value: 'true'
      # - name: OTEL_EXPORTER_OTLP_PROTOCOL
      #   value: http/protobuf 
      # - name: "OTEL_PYTHON_LOG_FORMAT"
      #   value: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
      - name: "OTEL_PYTHON_LOG_LEVEL"
        value: "info"
      # - name: OTEL_LOGS_EXPORTER
      #   # value: otlp_proto_http
      #   value: http/protobuf
      # - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
      #   value: 'true'
      # - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
      #   value: http/protobuf
      # - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
      #   value: http/protobuf
      # - name: OTEL_EXPORTER_OTLP_PROTOCOL
      #   value: http/protobuf
      # - name: OTEL_EXPORTER_OTLP_ENDPOINT
      #   value: http://daemonset-collector.opentelemetry-collectors:4318
      # - name: "OTEL_PYTHON_LOG_CORRELATION"
      #   value: "true"
  #     # - name: "OTEL_PYTHON_LOG_FORMAT"
  #     #   value: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
  #   #     # value: "%(asctime)s [trace_id=%(otelTraceID)s span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s] - %(message)s"
      # - name: "OTEL_PYTHON_LOG_LEVEL"
      #   value: "debug"